remove Stream impl on Incoming
With both `Stream` and `Iterator` implemented on `Incoming`, if you try
to get the next incoming connection asynchronously using the `next`
method in the `StreamExt` trait you end up with the following error due
to `next` method also existing in the `Iterator` trait:

```
error[E0034]: multiple applicable items in scope
  --> tests/async.rs:68:64
   |
68 |         let mut listener_socket = block_on(listener.incoming().next::<StreamExt>()).unwrap()?;
   |                                                                ^^^^ multiple `next` found
   |
   = note: candidate #1 is defined in an impl of the trait `futures_util::stream::stream::StreamExt` for the type `_`
   = note: candidate #2 is defined in an impl of the trait `std::iter::Iterator` for the type `memory_socket::Incoming<'_>`
```

In order to avoid user's from having to disambiguate between the two
`next` methods, remove the `Stream` impl on `Incoming` and instead
introduce the type `IncomingStream`, obtained from calling
`MemoryListener::incoming_stream`  which implements the `Stream` trait.